# Generated by Django 2.1.3 on 2018-11-10 20:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name to display to users', max_length=30, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('end_message', models.TextField(blank=True, help_text='The message to display at the end of the puzzle, upon successful completion. The puzzle end is reached when the user encouters a Question without a next_question field!')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A short name to display to users', max_length=30, unique=True)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=50)),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='puzzlify.Question')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzlify.Puzzle')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='first_question',
            field=models.ForeignKey(blank=True, help_text="What should be the first question to start this puzzle? If not set, the puzzle can't start", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='puzzlify.Question'),
        ),
    ]
