# Generated by Django 2.1.3 on 2018-11-10 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='first_question',
            field=models.ForeignKey(blank=True, help_text="What should be the first question to start this puzzle? If not set, the puzzle can't be played. Okay to come back and set this field later.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='puzzlify.Question'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='key',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
