# Generated by Django 2.1.3 on 2018-11-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlify', '0002_auto_20181110_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='key',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.SlugField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, help_text='If answered correctly, what should the next question be? Okay to come back and set this field later.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='puzzlify.Question'),
        ),
    ]
