# Generated by Django 2.1.3 on 2018-11-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlify', '0003_auto_20181110_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.CharField(default='', help_text="One or more valid answers, separated by commas. E.g. 'one,zero,1'", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.SlugField(help_text='Use something nice, this will be part of visible URLs', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text="A question, challenge or hint that the user must answer. E.g. 'What's the first number?'"),
        ),
    ]
