# Generated by Django 2.1.3 on 2018-11-11 02:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlify', '0004_auto_20181111_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='end_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
