# Generated by Django 2.1.3 on 2018-11-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlify', '0005_puzzle_end_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='description',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='start_message',
            field=models.TextField(default='', help_text='The message to display at the start of the puzzle.'),
            preserve_default=False,
        ),
    ]
